name: Sync to GitLab
on:
  push:
    branches:
      - master
      - develop
      - dev

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to GitLab
        uses: kulla/sync-to-gitlab@v1
        with:
          owner: stephan_kulla
          repository_name: serlo-evaluations
          token: ${{ secrets.GITLAB_TOKEN }}
